["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
main = [
    "./src/tokens/Avatar/Avatar.cairo",
]
points = [
    "./src/tokens/Points/Points.cairo",
]
achievements = [
    "./src/tokens/Achievements/Achievements.cairo",
]

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src"]
