[project]
protostar-version = "0.7.0"
lib-path = "lib"
cairo-path = ["./lib/cairo_contracts/src", "./lib/starknet_plugin_account/contracts"]

[contracts]
account = ["lib/cartridge_controller/src/account/PluginAccount.cairo"]
account_proxy = ["lib/cartridge_controller/src/upgrade/Proxy.cairo"]
achievements = ["src/tokens/achievements/Achievements.cairo"]
avatar = ["src/tokens/avatar/Avatar.cairo"]
controller = ["lib/cartridge_controller/src/controller/Controller.cairo"]
experience = ["src/tokens/experience/Experience.cairo"]
proxy = ["lib/cairo_contracts/src/openzeppelin/upgrades/presets/Proxy.cairo"]
