[project]
protostar-version = "0.7.0"
lib-path = "lib"
cairo-path = ["./lib/cairo_contracts/src"]

[contracts]
achievements = ["src/tokens/achievements/Achievements.cairo"]
avatar = ["src/tokens/Avatar/Avatar.cairo"]
experience = ["src/tokens/experience/Experience.cairo"]
